language: python

python:
  - 3.6

env:

  - DJANGO=2.0
  - DJANGO=2.1


sudo: false

install:
  - pip install tox-travis
  - pip install "coverage<=4.0" codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}"

after_success:
  - coverage combine
  - codecov
